Module2 task1
htmlacademy-javascript/1028665-keksobooking-24 pull request #2
Opened 2021-09-27 08:30 UTC by dapishta

2021-09-27 12:36 UTC, babtshe requested changes
Перед отправкой пуллреквеста на ревью хорошо править ошибки линтера:
![image](https://user-images.githubusercontent.com/30229773/134909058-0cd67b9e-63fc-4e14-9801-c6325e00eddc.png)

2021-09-27 12:36 UTC, babtshe commented on index.html
> +</script>
внутри тега не будет содержимого. Можно оставить закрывающий тег на одной строке с открывающим.

2021-09-27 12:36 UTC, babtshe commented on js/main.js
> +      return 'Please choose not equal min and max numbers';
почему числа не могут быть равны?

2021-09-27 12:36 UTC, babtshe commented on js/main.js
> +      return 'Please choose a range where min is less than max';
из названия функции следует, что она возвращает число, а тут вдруг приходит строка - не нужно так делать. 
В такой ситуации есть несколько подходов. Можно либо выбрасывать явную ошибку, либо научить функцию самостоятельно менять числа местами.

2021-09-27 12:36 UTC, babtshe commented on js/main.js
> +  }
Можно обойтись без этой проверки, внутри `toFixed` есть встроенная.

2021-09-27 12:36 UTC, babtshe commented on js/main.js
> +// https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed
комментарий с источниками можно выпилить, так как это встроенные методы. Есть смысл добавлять такие ссылки, когда используется какая-то внешняя библиотека, и то только в тех случаях когда дока важна для понимания происходящего в коде.

2021-09-27 12:36 UTC, babtshe commented on js/main.js
> +function getRandomFractionalNumber (min, max, numberOfSymbolsAfterComma) {
для параметра с количеством знаков после запятой можно задать значение по умолчанию. Тогда одну и ту же функцию можно будет использовать и для получения целых и для дробных чисел.

2021-09-28 04:52 UTC, dapishta commented on js/main.js
> +  }
В новом пулреквесте оставила эту проверку, потому что не нашла как пользоваться встроенной в toFixed - он просто выдает ошибку если указываешь отрицательное число.

2021-09-28 08:27 UTC, babtshe requested changes

2021-09-28 08:27 UTC, babtshe commented on js/main.js
> +    return NaN;
Стоит глянуть [доку по работе с ошибками](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error).

Фактически при выбросе явной ошибки дальнейшая работа программы прекращается. (это не всегда так, тут есть свои ньюансы). И такие ошибки это именно сигнал для разработчика, что что-то пошло не так. Нет необходимости показывать их пользователю.
Если же речь идёт о пользовательском вводе, как правило есть смысл поправить ошибки за него.

2021-09-28 08:27 UTC, babtshe commented on js/main.js
> +    max = swap;
Есть более [удобные способы](https://dmitripavlutin.com/swap-variables-javascript/) поменять значения переменных местами.

Обрати внимание, переопределение значений параметров функции - [плохая практика](https://spin.atomicobject.com/2011/04/10/javascript-don-t-reassign-your-function-arguments/).

2021-09-28 08:27 UTC, babtshe commented on js/main.js
> +    return NaN;
тут можно использовать стандартную ошибку встроенную в метод.

2021-09-28 11:10 UTC, babtshe approved these changes

2021-09-28 11:10 UTC, merged