Сделала задание по генерированию фейковых данных
htmlacademy-javascript/1028665-keksobooking-24 pull request #3
Opened 2021-10-04 08:35 UTC by dapishta

2021-10-04 09:48 UTC, babtshe requested changes
Чтобы сохранить историю коммитов в чистоте, можно запускать тесты локально перед отправкой:
![image](https://user-images.githubusercontent.com/30229773/135829937-1e074ae8-daaa-4d10-9680-86f2d93c3ed2.png)

Не стоит отменять правила ESLint. На данном этапе максимум можно отключить предупреждение о неиспользуемой переменной для массива объявлений. Всё остальное хорошо бы вернуть.

2021-10-04 09:48 UTC, babtshe commented on js/main.js
> +/* eslint-disable prefer-template */
зачем здесь эта штуковина?

2021-10-04 09:48 UTC, babtshe commented on js/main.js
> +const RANDOM_MAX_OTHER= 10;
какой же это рандом, когда тут вполне себе постоянные значения? Можно исключить лишнее из названия.

2021-10-04 09:48 UTC, babtshe commented on js/main.js
> +const TYPE = [
обрати внимание на критерий по именованию массивов.

2021-10-04 09:48 UTC, babtshe commented on js/main.js
> +const CHECKIN = [
❗

2021-10-04 09:48 UTC, babtshe commented on js/main.js
> +];
нужно ли тут повторять префикс в каждой строке?

2021-10-04 09:48 UTC, babtshe commented on js/main.js
> +// Functions
очевидных комментариев лучше избегать

2021-10-04 09:48 UTC, babtshe commented on js/main.js
> +  }
можно сократить условие с помощью шаблонных строк и тернарного оператора.

2021-10-04 09:48 UTC, babtshe commented on js/main.js
> +function generateAvatar () {
какие-то функции содержат в названии `get` а какие-то `generate`. При этом и те и те возвращают какие-то значения. Есть смысл сделать названия единообразными.

2021-10-04 09:48 UTC, babtshe commented on js/main.js
> +  const featureList = FEATURES.slice();
❗

2021-10-04 09:48 UTC, babtshe commented on js/main.js
> +  }
Есть смысл глянуть перемешивание Фишера-Йетса для получения случайного массива.

2021-10-04 09:48 UTC, babtshe commented on js/main.js
> +      // eslint-disable-next-line prefer-template
❗

2021-10-04 09:55 UTC, dapishta commented on js/main.js
> +/* eslint-disable prefer-template */
еслинт не дает писать строку так: 
'img/avatars/user0' + avatarRandomNumber + '.png'

хочет вместо этого писать вот так: 
`img/avatars/user0${  avatarRandomNumber  }.png`

Первый способ как-то пока пока понятнее, но могу использовать второй вариант. Как лучше?

2021-10-04 09:56 UTC, dapishta commented on js/main.js
> +const RANDOM_MAX_OTHER= 10;
В задании указано любое положительное число и если совсем любое тестовые данные получаются странные типа 1458989893 комнат, поэтому я подумала можно для них задать примерные макс значения. 

Если такой подход ок, то я могу убрать из названий Random

2021-10-04 09:58 UTC, dapishta commented on js/main.js
> +const CHECKIN = [
Что это значит?

2021-10-04 09:59 UTC, dapishta commented on js/main.js
> +];
А почему не стоит давать ссылки целиком? вдруг понадобятся фотки из другого хранилища как тестовые данные?

2021-10-04 09:59 UTC, dapishta commented on js/main.js
> +  const featureList = FEATURES.slice();
Что значит восклицательный знак?

2021-10-04 10:37 UTC, babtshe commented on js/main.js
> +/* eslint-disable prefer-template */
на этом интенсиве второй вариант

2021-10-04 10:53 UTC, babtshe commented on js/main.js
> +const CHECKIN = [
критерий по именованию массивов.

2021-10-04 10:54 UTC, babtshe commented on js/main.js
> +];
в данном случае не понадобятся. Но можно оставить и так.

2021-10-04 10:54 UTC, babtshe commented on js/main.js
> +  const featureList = FEATURES.slice();
критерий по именованию массивов.

2021-10-05 12:40 UTC, babtshe requested changes

2021-10-05 12:40 UTC, babtshe commented on js/main.js
> +const types = [
вполне можно оставить константой, главное следить за множественным числом в названии.

2021-10-05 12:40 UTC, babtshe commented on js/main.js
> +    : avatar = `img/avatars/user${  avatarRandomNumber  }.png`;
уже получше, можно ещё сократить, если тернарник убрать внутрь.
```
const slogan = `Приходите, ${ age > 18 ? `мы вам рады` : `когда подрастёте`}!`;
```

2021-10-05 12:40 UTC, babtshe commented on js/main.js
> +  return shuffledFeatures.slice(0,featuresNumber);
хорошо бы везде ставить пробелы между параметрами при вызове функций. Где-то есть, а где-то нету - не хватает единообразия.

2021-10-06 14:29 UTC, merged